### ISSUE TITLE
Datastax 3.x support

### ISSUE THREAD

**Issue by feedhandler** [aws-samples/amazon-keyspaces-java-driver-helpers#1]
Hi,
do you have a version of this library that will work with the datastax v3.x API?
Thanks

**Comment by michaelraney** [comment]
Hi I put in a version of the retry policy for the v3 driver. Since it uses a different dependency I commented out the code. For the throttler, that functionality is not available in 3.x drivers. https://github.com/aws-samples/amazon-keyspaces-java-driver-helpers/blob/main/src/main/java/com/aws/ssa/keyspaces/retry/AmazonKeyspacesRetryPolicy_driver_v3.java

**Comment by james-deee** [comment]
@michaelraney what aboiut the LoadBalancer? Do you have one for V3?

**Comment by michaelraney** [comment]
@james-deee sorry for the late response. You can use DCawareRoundRObin without TOkenAwareness.
